enum RouterCategories {
    agendaJobs = 'agenda-jobs',
    feedbacks = 'feedbacks',
    users = 'users',
    user = 'user',
    soloStreaks = 'solo-streaks',
    teamStreaks = 'team-streaks',
    streakRecommendations = 'streak-recommendations',
    completeSoloStreakTasks = 'complete-solo-streak-tasks',
    incompleteSoloStreakTasks = 'incomplete-solo-streak-tasks',
    completeTeamMemberStreakTasks = 'complete-team-member-streak-tasks',
    incompleteTeamMemberStreakTasks = 'incomplete-team-member-streak-tasks',
    completeTeamStreaks = 'complete-team-streak-tasks',
    incompleteTeamStreaks = 'incomplete-team-streaks',
    test = 'test',
    stripe = 'stripe',
    friends = 'friends',
    streakTrackingEvents = 'streak-tracking-events',
    teamMemberStreaks = 'team-member-streaks',
    friendRequests = 'friend-requests',
    dailyJobs = 'daily-jobs',
    emails = 'emails',
    profileImages = 'profile-images',
    badges = 'badges',
}

export default RouterCategories;
